### ISSUE TITLE
移植到1.18

### ISSUE THREAD

**Issue by Jamesdsj** [351768593/MinecraftTinkersThings#3]
你好，我浏览了你的模组，感觉很棒。我注意到从去年2月起模组就再没有更新。
你有1.18的更新计划吗？如果没有，我想把你的模组内容移植进我的模组“匠魂校准”里(www.mcmod.cn/class/10374.html)，在此征求你的同意

**Comment by FirokOtaku** [comment]
我其实有在断断续续接触 1.18、1.19 及更高版本的 mod 开发,
准备等 *神秘时代7* 出来之后把内容移植到高版本,
重做成神秘附属.

如果你有兴趣做移植,
在 mod 说明页面或匠魂手册页面内提一嘴创意源 / 移植来源即可.

另外如果有需要直接用到现有代码,
遵循现有的开源协议 (GPLv3) 的各类事项即可.

**Comment by Jamesdsj** [comment]
彳亍
谢谢啦
